version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "10010:80"
    volumes:
      - ./frontend/src:/usr/local/apache2/htdocs
    depends_on:
      - backend
    environment:
      - FLASK_APP=app.main
      - BACKEND_URL=http://backend:8000

  backend:
    build: ./backend
    ports:
      - "20010:8000"
    depends_on:
      - db
    environment:
      - MONGODB_URL=mongodb://db:27017/liquordb
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: mongo:latest
    ports:
      - "20011:27017"
    volumes:
      - mongodb_data:/data/db

  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    ports:
      - "10011:10011"
    volumes:
      - ./mobile:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_APP_ENV=production
    networks:
      - default
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge 